import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import GeneralDrawer from '@/components/generalDrawer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <GeneralDrawer />
        <div className="flex-1 overflow-hidden">
          <div className="container mx-auto h-full flex flex-col">
            <main className="flex h-screen pt-16 pb-4">
              <div className="w-full">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
